### ISSUE TITLE
Investigate packaging options for webHMI

### ISSUE THREAD

**Issue by AndrewMusser** [loupeteam/Loupe-UX#10]
### Problem statement
We want to package webHMI as a module that can be installed from an NPM registry wherever it's needed. The package that gets imported needs to be compatible with a browser-based app (i.e. via live-server) and a node-based app (i.e. electron). These two platforms have different import mechanisms. 

### Specific issues to address
- How to reference the webHMI files that got installed from the app? We prefer to be able to import them via JS directly, rather than having to include an additional <script> tag in html. 
- What path to use when referencing the installed files? With an NPM install, the files get nested inside the node_modules folder, but we'd still like to be able to reference via package name instead of absolute path. Something like `import * as WEBHMI from "webhmi"`. [JS importmaps](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script/type/importmap) may be a good candidate for this. 
- We may need to create several built versions of the package in a dist folder, using something like [parcel](https://parceljs.org/). This may be necessary for it to work cross-platform. Investigate parcel, how it handles building multiple versions of a library, and how the client logic (i.e. the app) knows which bundled version to pick from the dist folder. 

### Desired results
- An updated webHMI package (linked to this repo) that is cross-platform.
- [Maybe] A script for building webHMI using parcel.
- A defined mechanism for importing webHMI into an app.

**Comment by Joshpolansky** [comment]
I believe this is a solved problem at this point. We will NPM install it then get it from the node_modules folder.
